package engine

const (
	QInsertSessionData = `
		INSERT INTO SESSION_DATA(SESSION_ID, DATABASE_ID, DATABASE_LINK, DATABASE_DATA, DATA_STATUS, DATABASE_CON_ID)
		VALUES (%d, %d, %d, %d, %d, "%s");
	`

	QInsertSessionDataLog = `
		INSERT INTO SESSION_DATA(SESSION_ID, CON_ID, LOG)
		VALUES(%d, "%s", "%s");
	`

	QUpdateErrorStat = `
		UPDATE SESSION_DTL SET
			VALUE = VALUE + 1
		WHERE SESSION_ID = %d AND KEY = 'R1E';
	`

	QFinishSession = `
		UPDATE SESSION SET
			STATUS = 23,
			FINISH_TIME = CURRENT_TIMESTAMP
		WHERE ID = %d;
	`

	QGetComboListBatch = `
		SELECT 
			DLD.ID, DLD.DATABASE_LINK, DLD.DATA, DLD.CON_ID 
		FROM DATABASE_LINK_DATA DLD
		WHERE DLD.DATABASE_ID = $1 AND DLD.CON_ID > $2 LIMIT $3
	`

	QGetMaxConId            = "SELECT COALESCE(MAX(DATABASE_CON_ID), '') M FROM SESSION_DATA WHERE SESSION_ID = $1"
	QGetComboListBatchStart = `
		SELECT 
			ID, DATABASE_LINK, DATA, CON_ID 
		FROM (
			SELECT CON_ID C, DATABASE_ID D FROM DATABASE_LINK_DATA
			WHERE DATABASE_ID = $1 AND CON_ID < $2
			EXCEPT 
			SELECT DATABASE_CON_ID C, DATABASE_ID D FROM SESSION_DATA
			WHERE SESSION_ID = $3
		) A
		INNER JOIN DATABASE_LINK_DATA DLD ON DLD.DATABASE_ID = A.D AND DLD.CON_ID = A.C

		UNION

		SELECT 
			ID, DATABASE_LINK, DATA, CON_ID 
		FROM (
			SELECT 
				DLD.ID, DLD.DATABASE_LINK, DLD.DATA, DLD.CON_ID
			FROM DATABASE_LINK_DATA DLD
			WHERE DLD.DATABASE_ID = $4 AND DLD.CON_ID > $5
			LIMIT $6
		)	
	`

	QStartSession = `
		INSERT INTO SESSION_DTL(SESSION_ID, KEY, NAME, VALUE)
		SELECT 
			S.ID, 'R1E', 'Ошибки', '0' 
		FROM SESSION S
		WHERE S.ID = $1 AND START_TIME IS NULL;
		
		UPDATE SESSION SET
			STATUS = 22,
			ERRORS = NULL,
			START_TIME = IIF(START_TIME IS NULL, CURRENT_TIMESTAMP, START_TIME) 
		WHERE ID = $2;	
	`

	QGetAllAliveSessions = `
	SELECT 
		ID ID, STATUS S, WORKER_COUNT W,
		COALESCE(DATABASE_ID, -1) DATABASE_ID, 
		COALESCE(MODULE_ID,   -1) MODULE_ID, 
		COALESCE(PROXY_ID,    -1) PROXY_ID
	FROM SESSION WHERE STATUS = 22 OR ID IN `

	QGetProxyInfo = `
		SELECT 
			P.INTERVAL, P.TIMEOUT, P.USE_UPDATE, 
			PL.ID, PL.LINK, PL.LINK_TYPE, PL.PROXY_TYPE 
		FROM PROXY P 
		INNER JOIN PROXY_LINK PL ON P.ID = PL.PROXY_ID
		WHERE P.ID = $1
	`

	QGetSessionProxys = "SELECT * FROM SESSION_PROXY WHERE SESSION_ID = $1"

	QGetSessionProxyDTL = `
		SELECT * FROM SESSION_DTL SD
		WHERE SD.SESSION_ID = $1 AND SD.KEY = 'P1T'
	`

	QSetSessionError = `
		UPDATE SESSION SET
			STATUS = 13,
			ERRORS = $1
		WHERE ID = $2;
	`

	QGetProxys = `
		SELECT 
			PLD.HOST, PLD.PORT, PL.PROXY_TYPE type
		FROM PROXY_LINK_DATA PLD
		INNER JOIN PROXY_LINK PL ON PL.ID = PLD.PROXY_LINK
		WHERE PLD.PROXY_ID = $1 AND PLD.PROXY_LINK = $2
	`
)
